version: '3'

services:
  ynab-mono:
    build:
      context: .
      args:
        monoWebhookPort: ${MONO_WEBHOOK_PORT}
    restart: unless-stopped
    working_dir: /opt/app
    command: java -jar ynab-mono.jar --set-webhook --settings settings.json --mono-webhook-url ${MONO_WEBHOOK_URL} --mono-webhook-port ${MONO_WEBHOOK_PORT}
    ports:
      - ${OUTER_PORT}:${MONO_WEBHOOK_PORT}
    volumes:
      - ${SETTINGS_FILE_PATH}:/opt/app/settings.json:ro
