version: '3'

services:
  ynab-mono:
    build: .
    restart: unless-stopped
    working_dir: /opt/app
    command: java -jar ynab-mono.jar --set-webhook --settings settings.json --mono-webhook-url ${MONO_WEBHOOK_URL}
    environment:
      - OUTER_PORT=3332
    ports:
      - ${OUTER_PORT}:80
    volumes:
      - ${SETTINGS_FILE_PATH}:/opt/app/settings.json:ro
